### ISSUE TITLE
Doesn't work in Atom 1.23.1

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit-atom#17]
Hi,

**uikit-atom 0.2.2** autocomplete doesn't work in **Atom 1.23.1**

**Comment by dasdeck** [comment]
hmm. Just tested it here. Seems to work just fine. Can you give me some specifics?

**Comment by plantalabs** [comment]
uikit-atom 0.2.2 autocomplete doesn't work in Atom 1.23.1

i am using linux solus project, atom 1.23.4 x64, uikit plugin 0.3.1

still doesnt work, when i type for example a class. it do nothing

**Comment by viocassel** [comment]
Hi @dasdeck 
The plugin does not work in `.php` files...

**Comment by plantalabs** [comment]
confirmed on 1.23.3

1)not working well on php files 
2)has a strange behaviuor

example
when i type : "width" it suggest diferent classes i choose one (uk-width-1-2) and complete fine: "uk-width-1-2"

when i type: 1-2 it suggest diferent classes, i choose one (uk-width-1-2) and complete "**1-2**uk-width-1-2"

**Comment by plantalabs** [comment]
when i turn fuzzy filter false, it complete better

**Comment by plantalabs** [comment]
only on php files +1.

**Comment by dasdeck** [comment]
Hey! This seems to be related to this Atom issue:

https://github.com/atom/autocomplete-plus/issues/939

I'll upload a workaround in a few minutes.

Cheers!

**Comment by viocassel** [comment]
Thanks @dasdeck !

**Comment by plantalabs** [comment]
it works!!
